server:
  port: 8761

spring:
  application:
    name: discovery-server
  # Disable database auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

# Optional: Configure logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO