server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive  # Force reactive application type
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
        - id: theatre-service
          uri: lb://theatre-service
          predicates:
            - Path=/api/theatres/**
        - id: show-service
          uri: lb://show-service
          predicates:
            - Path=/api/shows/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

  # Disable database auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka